### PR TITLE
Fix 404 rendering instead of returning 1011 error

### LINKED ISSUE #86: Worker throwing exception on non-existent routes
[For example](https://workers.cloudflare.com/built-with/this-does-not-exist)

### PR DESCRIPTION
**Pull request by signalnerve**
This PR fixes a few issues with the way the Workers script was written for this project -- when an asset isn't able to be found, it now correctly renders the route `/built-with/404/index.html`. Hooray for error pages!

Closes #86

### CODE REVIEW

File: workers-site/index.js [hunk 1]
```diff
@@ -53,17 +53,19 @@ async function handleEvent(event) {
         bypassCache: true,
       }
     }
-    return hydrateEdgeState({
-      response: getAssetFromKV(event, options),
-      state: transformBookmark(event.request),
-    })
+    const response = await getAssetFromKV(event, options)
+    const state = await transformBookmark(event.request)
```
Comment (signalnerve) [inline workers-site/index.js]: The `await` calls need to happen here so that they're caught by this `try`/`catch` block!

**Comment by EverlastingBugstopper** [comment]
nice

**Comment by adamschwartz** [comment]
Looin good:

image
